[build]
  command = "npm run build:growth"
  publish = "dist-growth"

[functions]
  directory = "netlify/growth-functions"

[database.migrations]
  path = "deploy/growth/netlify/database/migrations"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
